import type { BlogPost } from "./blog";

export const BLOG_POSTS_EN: BlogPost[] = [
  {
    slug: "karta-pobytu-czasowego-poradnik-2026",
    locale: "en",
    title: "Temporary Residence Card in Poland 2026 \u2014 Complete Step-by-Step Guide",
    description: "How to get a temporary residence card in Poland in 2026? Required documents, costs, processing time and common mistakes. A practical guide by getpermit.pl.",
    date: "2026-04-15",
    imageUrl: "/blog/karta-pobytu-czasowego.svg",
    imageAlt: "Temporary residence card in Poland \u2014 documents and legalization procedure",
    author: "Grzegorz St\u0119pie\u0144, UTM Group",
    toc: [
      { id: "czym-jest", title: "What is a temporary residence card" },
      { id: "kto-moze", title: "Who can apply" },
      { id: "dokumenty", title: "Required documents" },
      { id: "procedura", title: "Step-by-step procedure" },
      { id: "koszty", title: "Costs and fees in 2026" },
      { id: "czas-oczekiwania", title: "Processing time" },
      { id: "najczestsze-bledy", title: "Common mistakes" },
      { id: "faq", title: "FAQ" },
    ],
    sections: [
      { id: "czym-jest", heading: "What is a temporary residence card and what rights does it grant", content: `<p>A temporary residence card (karta pobytu czasowego) is a document issued to foreigners who intend to stay in Poland for <strong>more than 3 months</strong>. It confirms legal residence and allows free travel within the Schengen zone without an additional visa.</p><p>The permit may be granted for a period of 3 months to <strong>3 years</strong>. It entitles the holder to:</p><ul><li>Legal residence in Poland</li><li>Employment (if the permit covers work)</li><li>Travel within the Schengen area for up to 90 days in any 180-day period</li><li>Access to public healthcare (with valid insurance)</li><li>Applying for a PESEL number</li></ul>` },
      { id: "kto-moze", heading: "Who can apply for a temporary residence card in Poland", content: `<p>Any foreigner legally staying in Poland who intends to remain for more than 3 months may submit an application. The most common purposes of stay:</p><ul><li><strong>Work</strong> \u2014 employment contract or unified residence and work permit</li><li><strong>Business activity</strong> \u2014 company registration (sp. z o.o., sole proprietorship)</li><li><strong>Studies</strong> \u2014 full-time studies at a Polish university</li><li><strong>Family reunification</strong> \u2014 joining a spouse or parent with a residence permit</li></ul><p>The application must be submitted <strong>no later than the last day of legal stay</strong>. Since 2026, applications are submitted exclusively through the <a href="/en/blog/wnioski-pobytowe-mos-2026">MOS system</a>.</p>` },
      { id: "dokumenty", heading: "Documents required for a temporary residence card application", content: `<p>The document list depends on the purpose of stay. Common requirements include:</p><ul><li>Completed application form</li><li>4 biometric photos (35\u00d745 mm)</li><li>Passport copy (all pages with data)</li><li>Proof of stamp duty payment (340-440 PLN)</li><li>Health insurance</li><li>Proof of accommodation</li><li>Source of income documentation</li></ul><p>Additional documents for employees: employer certificate, starost's information (labor market test), attachment no. 1. <a href="/en/uslugi/zezwolenie-na-pobyt-czasowy">Check the full list for your case</a>.</p>` },
      { id: "procedura", heading: "Procedure for obtaining a residence card \u2014 step by step", content: `<p>The process consists of the following stages:</p><ol><li><strong>Document preparation</strong> \u2014 collecting all required attachments</li><li><strong>Application submission</strong> \u2014 via MOS system or in person at the voivodeship office</li><li><strong>Fingerprint collection</strong> \u2014 biometrics taken at the office</li><li><strong>Passport stamp</strong> \u2014 confirms application submission, legalizes stay during proceedings</li><li><strong>Waiting for decision</strong> \u2014 the office may request additional documents</li><li><strong>Card collection</strong> \u2014 after a positive decision, the card is produced within 2\u20134 weeks</li></ol>` },
      { id: "koszty", heading: "Costs of obtaining a temporary residence card in 2026", content: `<p>Fees related to temporary residence cards in 2026:</p><table><thead><tr><th>Fee</th><th>Amount</th></tr></thead><tbody><tr><td>Stamp duty \u2014 temporary residence</td><td><strong>340 PLN</strong></td></tr><tr><td>Stamp duty \u2014 residence and work (unified permit)</td><td><strong>440 PLN</strong></td></tr><tr><td>Card issuance</td><td><strong>100 PLN</strong></td></tr><tr><td>Sworn translations (approximate)</td><td>50\u2013150 PLN per page</td></tr></tbody></table><p>Total cost including translations and legal help is typically <strong>800 to 2,500 PLN</strong>. <a href="/en/kontakt">Contact us for a free quote</a>.</p>` },
      { id: "czas-oczekiwania", heading: "How long does it take to process a residence card application", content: `<p>The statutory processing time is <strong>60 days</strong> from submitting complete documentation. In practice, waiting times depend on the voivodeship office:</p><ul><li><strong>Masovian (Warsaw)</strong> \u2014 4\u20138 months</li><li><strong>Lesser Poland (Krak\u00f3w)</strong> \u2014 3\u20136 months</li><li><strong>Lower Silesian (Wroc\u0142aw)</strong> \u2014 3\u20135 months</li><li><strong>Pomeranian (Gda\u0144sk)</strong> \u2014 2\u20134 months</li></ul><p>If the statutory deadline is exceeded, you can file an <strong>urgency complaint</strong>. <a href="/en/uslugi/ponaglenia-i-odwolania">We help with the appeals procedure</a>.</p>` },
      { id: "najczestsze-bledy", heading: "Most common mistakes in residence card applications", content: `<p>Based on our experience with 5,000+ cases, the most common mistakes are:</p><ol><li><strong>Late submission</strong> \u2014 the application must be filed before visa or visa-free stay expires</li><li><strong>Missing sworn translations</strong> \u2014 all foreign documents require certified translation</li><li><strong>Incomplete documentation</strong> \u2014 missing employer certificates or starost's information</li><li><strong>Form errors</strong> \u2014 spelling mistakes in personal data cause requests for correction</li><li><strong>Missing health insurance</strong> \u2014 often overlooked for contract workers</li></ol><p><a href="/en/uslugi/zezwolenie-na-pobyt-czasowy">Professional help eliminates the risk of refusal</a>.</p>` },
      { id: "faq", heading: "Frequently asked questions about temporary residence cards", content: `<div class="faq-list"><details><summary><strong>How much does a temporary residence card cost in 2026?</strong></summary><p>Stamp duty is 340 PLN (or 440 PLN for unified residence and work permit). Plus 100 PLN for card issuance. With translations and legal assistance, the total cost is 800\u20132,500 PLN.</p></details><details><summary><strong>Can I work while waiting for my residence card?</strong></summary><p>Yes. The passport stamp confirming application submission entitles you to legal work under the conditions specified in the application.</p></details><details><summary><strong>What if my application is rejected?</strong></summary><p>You can appeal to the Head of the Office for Foreigners within 14 days. We help with the appeals process with a 98% success rate.</p></details><details><summary><strong>How long is a temporary residence card valid?</strong></summary><p>It is issued for 3 months to 3 years, depending on the purpose of stay specified in the application.</p></details></div>` },
    ],
  },
  {
    slug: "karta-stalego-pobytu-jak-uzyskac",
    locale: "en",
    title: "Permanent Residence Card in Poland \u2014 Who Can Get It and How to Apply",
    description: "A permanent residence card grants the right to live in Poland indefinitely. Check conditions, documents and costs. Guide by getpermit.pl.",
    date: "2026-04-14",
    imageUrl: "/blog/karta-stalego-pobytu.svg",
    imageAlt: "Permanent residence card in Poland \u2014 procedure for obtaining the document",
    author: "Grzegorz St\u0119pie\u0144, UTM Group",
    toc: [
      { id: "czym-jest-staly", title: "What is a permanent residence card" },
      { id: "warunki", title: "Eligibility conditions" },
      { id: "dokumenty-staly", title: "Required documents" },
      { id: "koszty-staly", title: "Costs and timelines" },
      { id: "roznice", title: "Permanent residence vs EU long-term resident" },
      { id: "faq-staly", title: "FAQ" },
    ],
    sections: [
      { id: "czym-jest-staly", heading: "What is a permanent residence card and what rights does it grant", content: `<p>A permanent residence card (karta sta\u0142ego pobytu) confirms a foreigner's right to <strong>reside in Poland indefinitely</strong>. Unlike a temporary card, it does not require renewal every few years.</p><ul><li>Indefinite stay in Poland</li><li>Work without a work permit</li><li>Business activity on equal terms with Polish citizens</li><li>Public healthcare and education access</li><li>Eligibility for Polish citizenship</li></ul>` },
      { id: "warunki", heading: "Eligibility conditions for permanent residence", content: `<p>You may apply if you meet <strong>one of the following conditions</strong>:</p><ul><li><strong>Polish heritage</strong> \u2014 proven Polish roots (parents or grandparents were Polish citizens)</li><li><strong>Karta Polaka</strong> \u2014 holder intending to settle permanently in Poland</li><li><strong>Marriage to a Polish citizen</strong> \u2014 at least 3 years of marriage + 2 years of residence on a temporary card</li><li><strong>Victim of human trafficking</strong></li><li><strong>Child of a foreigner</strong> with permanent residence, born in Poland</li></ul><p><a href="/en/uslugi/pobyt-staly">Check if you qualify \u2014 free consultation</a>.</p>` },
      { id: "dokumenty-staly", heading: "Documents required for permanent residence application", content: `<p>Basic document set:</p><ul><li>Completed application form (2 copies)</li><li>4 biometric photos</li><li>Passport copy (all pages)</li><li>Stamp duty receipt (640 PLN)</li><li>Documents proving your eligibility basis</li></ul><p>All foreign documents require <a href="/en/uslugi/tlumaczenia-przysiegle-dokumentow">sworn translation</a> into Polish.</p>` },
      { id: "koszty-staly", heading: "Costs and processing time for permanent residence", content: `<p>Fees in 2026:</p><ul><li>Stamp duty: <strong>640 PLN</strong></li><li>Card issuance: <strong>100 PLN</strong></li><li>Sworn translations: from 50 PLN per page</li></ul><p>Processing time: <strong>3 to 12 months</strong>. Karta Polaka cases are typically processed faster.</p><p><a href="/en/kontakt">Book a free consultation \u2014 we'll prepare your application professionally</a>.</p>` },
      { id: "roznice", heading: "Permanent residence vs EU long-term resident \u2014 differences", content: `<table><thead><tr><th>Feature</th><th>Permanent residence</th><th>EU long-term resident</th></tr></thead><tbody><tr><td>Required stay in Poland</td><td>Not always (depends on basis)</td><td>Min. 5 years of uninterrupted stay</td></tr><tr><td>EU labor market access</td><td>Poland only</td><td>Right to work in other EU countries</td></tr><tr><td>Stamp duty</td><td>640 PLN</td><td>640 PLN</td></tr></tbody></table><p><a href="/en/uslugi/rezydent-dlugoterminowy-ue">Learn more about EU long-term resident status</a>.</p>` },
      { id: "faq-staly", heading: "FAQ \u2014 permanent residence card in Poland", content: `<div class="faq-list"><details><summary><strong>Does a permanent residence card grant Polish citizenship?</strong></summary><p>Not automatically, but after obtaining permanent residence you can apply for citizenship after meeting additional conditions (e.g., Polish language exam at B1 level).</p></details><details><summary><strong>How much does a permanent residence card cost?</strong></summary><p>Stamp duty: 640 PLN + 100 PLN for card issuance. With legal services and translations, the total is typically 1,200\u20133,000 PLN.</p></details><details><summary><strong>Can I lose permanent residence status?</strong></summary><p>Yes, if you leave Poland for more than 6 years or pose a threat to national security.</p></details></div>` },
    ],
  },
  {
    slug: "niebieska-karta-ue-blue-card-2026",
    locale: "en",
    title: "EU Blue Card in Poland 2026 \u2014 New Rules and Requirements",
    description: "EU Blue Card after 2025 changes. Who can get a Blue Card in Poland? Requirements, documents, costs and EU mobility benefits. Guide by getpermit.pl.",
    date: "2026-04-13",
    imageUrl: "/blog/niebieska-karta-ue.svg",
    imageAlt: "EU Blue Card for specialists in Poland",
    author: "Grzegorz St\u0119pie\u0144, UTM Group",
    toc: [
      { id: "czym-jest-blue", title: "What is the EU Blue Card" },
      { id: "nowe-zasady", title: "Changes from 2025" },
      { id: "wymagania-blue", title: "Requirements" },
      { id: "dokumenty-blue", title: "Required documents" },
      { id: "mobilnosc", title: "EU mobility" },
      { id: "blue-vs-czasowy", title: "Blue Card vs work permit" },
      { id: "faq-blue", title: "FAQ" },
    ],
    sections: [
      { id: "czym-jest-blue", heading: "What is the EU Blue Card and why you should get one", content: `<p>The EU Blue Card is a residence and work permit designed for <strong>highly qualified non-EU workers</strong>. Key advantages:</p><ul><li><strong>EU mobility</strong> \u2014 after 12 months, you can relocate to another EU member state</li><li><strong>Easier family reunification</strong></li><li><strong>Faster path to EU long-term resident</strong> \u2014 periods in different EU countries can be combined</li><li><strong>No labor market test</strong></li></ul>` },
      { id: "nowe-zasady", heading: "New EU Blue Card rules from 2025 \u2014 what changed", content: `<p>From <strong>June 1, 2025</strong>, revised rules apply. Key changes:</p><ul><li><strong>Lower salary threshold</strong> \u2014 1.0x average salary instead of 1.5x (0.8x for shortage occupations)</li><li><strong>Expanded qualifications</strong> \u2014 3 years of IT experience accepted instead of a degree</li><li><strong>Shorter contracts</strong> \u2014 minimum 6 months (previously 12)</li><li><strong>Short-term mobility</strong> \u2014 up to 90 days of work in another EU country without formalities</li></ul>` },
      { id: "wymagania-blue", heading: "Requirements for the EU Blue Card in Poland", content: `<ol><li><strong>Higher education</strong> (min. 3-year degree) <strong>or 3 years IT experience</strong> (from 2025)</li><li><strong>Employment contract</strong> for at least 6 months with a Polish employer</li><li><strong>Salary</strong> of at least 1.0x the average annual salary (~7,500 PLN gross/month in 2026)</li><li><strong>Health insurance</strong></li><li><strong>Place of residence</strong> in Poland</li></ol><p>IT specialists with 3 years of experience can apply <strong>without a university degree</strong>. <a href="/en/uslugi/eu-blue-card">Check details</a>.</p>` },
      { id: "dokumenty-blue", heading: "Documents required for the EU Blue Card application", content: `<ul><li>Completed application form</li><li>4 biometric photos</li><li>Passport copy</li><li>Employment contract or job promise</li><li>University degree (with nostrification if required) <strong>or</strong> proof of 3 years IT experience</li><li>Salary certificate meeting the threshold</li><li>Health insurance proof</li><li>Stamp duty: <strong>440 PLN</strong> + 100 PLN for card issuance</li></ul>` },
      { id: "mobilnosc", heading: "EU mobility with the Blue Card", content: `<ul><li><strong>Short-term</strong> (up to 90 days) \u2014 business trips without additional formalities</li><li><strong>Long-term</strong> \u2014 after 12 months you can apply for a Blue Card in another EU country on simplified terms</li><li><strong>Period accumulation</strong> \u2014 Blue Card periods in different EU countries count toward the 5-year requirement for EU long-term resident status</li></ul>` },
      { id: "blue-vs-czasowy", heading: "EU Blue Card vs residence and work permit \u2014 comparison", content: `<table><thead><tr><th>Feature</th><th>Blue Card</th><th>Residence & work</th></tr></thead><tbody><tr><td>Salary threshold</td><td>~7,500 PLN gross/mo</td><td>None</td></tr><tr><td>Education</td><td>Degree or 3yr IT exp.</td><td>Any</td></tr><tr><td>Labor market test</td><td>Not required</td><td>Required (with exceptions)</td></tr><tr><td>EU mobility</td><td>Yes</td><td>No</td></tr><tr><td>Processing time</td><td>1\u20133 months</td><td>3\u20136 months</td></tr></tbody></table><p><a href="/en/kontakt">Not sure which permit is right for you? Book a free consultation</a>.</p>` },
      { id: "faq-blue", heading: "FAQ \u2014 EU Blue Card in Poland", content: `<div class="faq-list"><details><summary><strong>What salary is required for a Blue Card in 2026?</strong></summary><p>The threshold is 1.0x the average annual salary, approximately 7,500 PLN gross per month in 2026. In shortage occupations (IT, engineering) the threshold is lower at 0.8x.</p></details><details><summary><strong>Can a programmer without a degree get a Blue Card?</strong></summary><p>Yes, since 2025 IT specialists with at least 3 years of professional experience can apply without a university degree.</p></details><details><summary><strong>How long does the Blue Card procedure take?</strong></summary><p>Typically 1\u20133 months, faster than a standard residence and work permit (3\u20136 months).</p></details></div>` },
    ],
  },
  {
    slug: "wnioski-pobytowe-mos-2026",
    locale: "en",
    title: "Online Residence Applications via MOS in 2026 \u2014 How the New System Works",
    description: "Since 2026, residence card applications in Poland are submitted through MOS. How to create an account, fill in the e-application and avoid mistakes. Guide by getpermit.pl.",
    date: "2026-04-12",
    imageUrl: "/blog/wnioski-mos.svg",
    imageAlt: "MOS system \u2014 online residence applications in Poland 2026",
    author: "Grzegorz St\u0119pie\u0144, UTM Group",
    toc: [
      { id: "czym-jest-mos", title: "What is MOS" },
      { id: "jak-zalozyc", title: "How to create an account" },
      { id: "jak-wypelnic", title: "How to fill in the e-application" },
      { id: "zalaczniki", title: "Adding attachments" },
      { id: "po-zlozeniu", title: "After submission" },
      { id: "problemy-mos", title: "Common MOS issues" },
      { id: "faq-mos", title: "FAQ" },
    ],
    sections: [
      { id: "czym-jest-mos", heading: "What is MOS \u2014 the Case Handling Module", content: `<p><strong>MOS (Modu\u0142 Obs\u0142ugi Spraw / Case Handling Module)</strong> is an electronic system launched in 2025 that became the <strong>mandatory channel for submitting residence applications</strong> in Poland from 2026. It replaced paper forms and in-person visits at voivodeship offices at the submission stage.</p><p>Through MOS you can apply for:</p><ul><li>Temporary residence permit</li><li>Permanent residence permit</li><li>EU long-term resident permit</li><li>Visa extension</li></ul><p>The system is available at <strong>mos.cudzoziemcy.gov.pl</strong> in Polish, English, Russian and Ukrainian.</p>` },
      { id: "jak-zalozyc", heading: "How to create an account in MOS", content: `<ol><li>Go to <strong>mos.cudzoziemcy.gov.pl</strong></li><li>Click \u201cCreate account\u201d</li><li>Enter your email and create a password</li><li>Confirm your email via the activation link</li><li>Complete your personal details (name, surname, passport number)</li></ol><p>The system allows <strong>saving draft versions</strong> and returning to them at any time.</p>` },
      { id: "jak-wypelnic", heading: "How to fill in the electronic residence application", content: `<p>The MOS form is divided into sections matching the traditional paper form:</p><ol><li><strong>Personal data</strong></li><li><strong>Passport details</strong></li><li><strong>Address in Poland</strong></li><li><strong>Purpose of stay</strong></li><li><strong>Employer data</strong> (if work-related)</li><li><strong>Additional information</strong></li></ol><p>The system <strong>validates data in real time</strong>. <a href="/en/kontakt">Need help filling in the application? Contact us</a>.</p>` },
      { id: "zalaczniki", heading: "Attachments \u2014 what and how to upload", content: `<p>MOS accepts files in PDF, JPG and PNG formats. Maximum <strong>10 MB</strong> per attachment. Required:</p><ul><li>Passport scan (all data pages)</li><li>Biometric photo (digital format)</li><li>Stamp duty payment confirmation</li><li>Documents confirming purpose of stay</li><li>Sworn translations of foreign documents</li></ul><p>Original documents must be presented in person during the <strong>fingerprint appointment</strong>.</p>` },
      { id: "po-zlozeniu", heading: "What happens after submitting via MOS", content: `<ol><li><strong>Case number</strong> assigned</li><li><strong>Electronic confirmation</strong> generated \u2014 equivalent of passport stamp</li><li><strong>Appointment invitation</strong> sent \u2014 for biometrics</li><li><strong>Supplement requests</strong> communicated via MOS and email</li><li><strong>Decision</strong> notification</li></ol>` },
      { id: "problemy-mos", heading: "Common MOS problems and solutions", content: `<ul><li><strong>System overload</strong> \u2014 try submitting in evening hours or on weekends</li><li><strong>Attachment issues</strong> \u2014 ensure files are under 10 MB in PDF/JPG format</li><li><strong>Validation errors</strong> \u2014 check date format (DD-MM-YYYY) and numbers</li><li><strong>Session timeout</strong> \u2014 system logs out after 30 minutes of inactivity; save drafts frequently</li></ul><p><a href="/en/kontakt">Our team can help you submit the application correctly</a>.</p>` },
      { id: "faq-mos", heading: "FAQ \u2014 residence applications via MOS", content: `<div class="faq-list"><details><summary><strong>Can I still submit a paper application?</strong></summary><p>Since 2026, paper applications are accepted only in exceptional cases (e.g., confirmed system failures). The standard channel is MOS exclusively.</p></details><details><summary><strong>Do I need to visit the office in person?</strong></summary><p>Yes \u2014 an in-person visit is required for fingerprint collection (biometrics). The application itself is submitted online.</p></details><details><summary><strong>What languages is MOS available in?</strong></summary><p>Polish, English, Russian and Ukrainian. The application form must be filled in Polish.</p></details></div>` },
    ],
  },
  {
    slug: "ile-kosztuje-karta-pobytu-2026",
    locale: "en",
    title: "How Much Does a Residence Card Cost in 2026? Full Price List",
    description: "Current residence card costs in 2026: stamp duty, card issuance, sworn translations and legal help. Price list and cost calculator by getpermit.pl.",
    date: "2026-04-11",
    imageUrl: "/blog/ile-kosztuje-karta-pobytu.svg",
    imageAlt: "Residence card costs in Poland 2026 \u2014 official fee price list",
    author: "Grzegorz St\u0119pie\u0144, UTM Group",
    toc: [
      { id: "oplaty-skarbowe", title: "Stamp duties" },
      { id: "wydanie-karty", title: "Card issuance cost" },
      { id: "tlumaczenia", title: "Sworn translations" },
      { id: "pomoc-prawna", title: "Legal assistance" },
      { id: "calkowity-koszt", title: "Total cost" },
      { id: "faq-koszty", title: "FAQ" },
    ],
    sections: [
      { id: "oplaty-skarbowe", heading: "Stamp duties for residence cards in 2026", content: `<table><thead><tr><th>Permit type</th><th>Stamp duty</th></tr></thead><tbody><tr><td>Temporary residence</td><td><strong>340 PLN</strong></td></tr><tr><td>Temporary residence and work (unified)</td><td><strong>440 PLN</strong></td></tr><tr><td>EU Blue Card</td><td><strong>440 PLN</strong></td></tr><tr><td>Permanent residence</td><td><strong>640 PLN</strong></td></tr><tr><td>EU long-term resident</td><td><strong>640 PLN</strong></td></tr><tr><td>Visa extension</td><td><strong>406 PLN</strong></td></tr></tbody></table><p>The fee must be paid <strong>before submitting the application</strong>.</p>` },
      { id: "wydanie-karty", heading: "Card issuance fee", content: `<p>After a positive decision, the office produces a plastic card. The issuance fee is <strong>100 PLN</strong> for all types. Production time: <strong>2\u20134 weeks</strong> from the decision.</p>` },
      { id: "tlumaczenia", heading: "Sworn translation costs", content: `<table><thead><tr><th>Document</th><th>Approximate cost</th></tr></thead><tbody><tr><td>Passport</td><td>50\u2013100 PLN</td></tr><tr><td>Birth certificate</td><td>60\u201380 PLN</td></tr><tr><td>Marriage certificate</td><td>60\u201380 PLN</td></tr><tr><td>University diploma</td><td>80\u2013150 PLN</td></tr></tbody></table><p>Total translation costs for a typical case: <strong>150\u2013400 PLN</strong>. <a href="/en/uslugi/tlumaczenia-przysiegle-dokumentow">We offer competitive translation prices</a>.</p>` },
      { id: "pomoc-prawna", heading: "Cost of professional legal assistance", content: `<ul><li><strong>Initial consultation</strong> \u2014 free (at getpermit.pl)</li><li><strong>Application preparation</strong> \u2014 from 600 PLN</li><li><strong>Full case handling</strong> \u2014 from 800 PLN</li><li><strong>Permanent / EU resident</strong> \u2014 from 1,200 PLN</li><li><strong>Urgency complaint / appeal</strong> \u2014 from 500 PLN</li></ul><p>Our success rate is <strong>98%</strong>. <a href="/en/kontakt">Book a free quote</a>.</p>` },
      { id: "calkowity-koszt", heading: "Total residence card cost \u2014 summary", content: `<table><thead><tr><th>Component</th><th>Temporary</th><th>Temp. + work</th><th>Permanent</th></tr></thead><tbody><tr><td>Stamp duty</td><td>340 PLN</td><td>440 PLN</td><td>640 PLN</td></tr><tr><td>Card issuance</td><td>100 PLN</td><td>100 PLN</td><td>100 PLN</td></tr><tr><td>Translations</td><td>150\u2013400 PLN</td><td>150\u2013400 PLN</td><td>200\u2013500 PLN</td></tr><tr><td>Legal help (optional)</td><td>from 600 PLN</td><td>from 800 PLN</td><td>from 1,200 PLN</td></tr><tr><td><strong>Total</strong></td><td><strong>590\u20131,440 PLN</strong></td><td><strong>690\u20131,740 PLN</strong></td><td><strong>940\u20132,440 PLN</strong></td></tr></tbody></table>` },
      { id: "faq-koszty", heading: "FAQ \u2014 residence card costs", content: `<div class="faq-list"><details><summary><strong>Is the stamp duty refunded if the application is rejected?</strong></summary><p>No. The stamp duty is non-refundable in case of a negative decision. That's why professional help is recommended to minimize the risk of rejection.</p></details><details><summary><strong>How much does a residence card cost for a Ukrainian citizen?</strong></summary><p>Fees are the same for all foreigners regardless of citizenship. Ukrainians under temporary protection may benefit from simplified procedures, but the fees remain standard.</p></details><details><summary><strong>Is the consultation at getpermit.pl really free?</strong></summary><p>Yes. The initial consultation is completely free and non-binding. We assess your situation, propose a strategy and provide an exact quote.</p></details></div>` },
    ],
  },
];
