import type { BlogPost } from "./blog";

export const BLOG_POSTS_EN: BlogPost[] = [
  {
    slug: "karta-pobytu-czasowego-poradnik-2026",
    locale: "en",
    title: "Temporary Residence Card in Poland 2026 \u2014 Complete Step-by-Step Guide",
    description: "How to get a temporary residence card in Poland in 2026? Required documents, costs, processing time and common mistakes. A practical guide by getpermit.pl.",
    date: "2026-04-15",
    imageUrl: "https://images.unsplash.com/photo-1473163928189-364b2c4e1135?w=1600&q=80",
    imageAlt: "Temporary residence card in Poland \u2014 documents and legalization procedure",
    author: "Grzegorz St\u0119pie\u0144, UTM Group",
    toc: [
      { id: "czym-jest", title: "What is a temporary residence card" },
      { id: "kto-moze", title: "Who can apply" },
      { id: "dokumenty", title: "Required documents" },
      { id: "procedura", title: "Step-by-step procedure" },
      { id: "koszty", title: "Costs and fees in 2026" },
      { id: "czas-oczekiwania", title: "Processing time" },
      { id: "najczestsze-bledy", title: "Common mistakes" },
      { id: "faq", title: "FAQ" },
    ],
    sections: [
      { id: "czym-jest", heading: "What is a temporary residence card and what rights does it grant", content: `<p>A temporary residence card (karta pobytu czasowego) is a document issued to foreigners who intend to stay in Poland for <strong>more than 3 months</strong>. It confirms legal residence and allows free travel within the Schengen zone without an additional visa.</p><p>The permit may be granted for a period of 3 months to <strong>3 years</strong>. It entitles the holder to:</p><ul><li>Legal residence in Poland</li><li>Employment (if the permit covers work)</li><li>Travel within the Schengen area for up to 90 days in any 180-day period</li><li>Access to public healthcare (with valid insurance)</li><li>Registering residence (zameldowanie)</li></ul>` },
      { id: "kto-moze", heading: "Who can apply for a temporary residence card in Poland", content: `<p>Any foreigner legally staying in Poland who intends to remain for more than 3 months may submit an application. The most common purposes of stay:</p><ul><li><strong>Work</strong> \u2014 employment contract or unified residence and work permit</li><li><strong>Business activity</strong> \u2014 company registration (sp. z o.o., sole proprietorship)</li><li><strong>Studies</strong> \u2014 full-time studies at a Polish university</li><li><strong>Family reunification</strong> \u2014 joining a spouse or parent with a residence permit</li></ul><p>The application must be submitted <strong>no later than the last day of legal stay</strong>. Since 2026, applications are submitted exclusively through the <a href="/en/blog/wnioski-pobytowe-mos-2026">MOS system</a>.</p>` },
      { id: "dokumenty", heading: "Documents required for a temporary residence card application", content: `<p>The document list depends on the purpose of stay. Common requirements include:</p><ul><li>Completed application form</li><li>Digital photograph (uploaded via the MOS system)</li><li>Passport copy (all pages with data)</li><li>Proof of stamp duty payment (340-440 PLN)</li><li>Health insurance</li><li>Proof of accommodation</li><li>Source of income documentation</li></ul><p>Additional documents for employees: employer certificate, attachment no. 1. <a href="/en/uslugi/zezwolenie-na-pobyt-czasowy">Check the full list for your case</a>.</p>` },
      { id: "procedura", heading: "Procedure for obtaining a residence card \u2014 step by step", content: `<p>The process consists of the following stages:</p><ol><li><strong>Document preparation</strong> \u2014 collecting all required attachments</li><li><strong>Application submission</strong> \u2014 exclusively via the MOS system (since April 27, 2025)</li><li><strong>Fingerprint collection</strong> \u2014 biometrics taken at the office</li><li><strong>Passport stamp</strong> \u2014 confirms application submission, legalizes stay during proceedings</li><li><strong>Waiting for decision</strong> \u2014 the office may request additional documents</li><li><strong>Card collection</strong> \u2014 after a positive decision, the card is produced by the office (timeframe depends on workload)</li></ol>` },
      { id: "koszty", heading: "Costs of obtaining a temporary residence card in 2026", content: `<p>Fees related to temporary residence cards in 2026:</p><table><thead><tr><th>Fee</th><th>Amount</th></tr></thead><tbody><tr><td>Stamp duty \u2014 temporary residence</td><td><strong>340 PLN</strong></td></tr><tr><td>Stamp duty \u2014 residence and work (unified permit)</td><td><strong>440 PLN</strong></td></tr><tr><td>Card issuance</td><td><strong>100 PLN</strong></td></tr><tr><td>Sworn translations (approximate)</td><td>50\u2013150 PLN per page</td></tr></tbody></table><p>Total cost including translations and legal help is typically <strong>800 to 2,500 PLN</strong>. <a href="/en/kontakt">Contact us for a quote</a>.</p>` },
      { id: "czas-oczekiwania", heading: "How long does it take to process a residence card application", content: `<p>The processing time for a temporary residence card application <strong>depends on the individual case and the workload of the voivodeship office</strong>. Each office processes applications at a different pace, and the waiting time is influenced by the completeness of documentation and the complexity of the case.</p><p>If the statutory deadline is exceeded, you can file an <strong>urgency complaint</strong>. <a href="/en/uslugi/ponaglenia-i-odwolania">We help with the appeals procedure</a>.</p>` },
      { id: "najczestsze-bledy", heading: "Most common mistakes in residence card applications", content: `<p>Based on our experience with 5,000+ cases, the most common mistakes are:</p><ol><li><strong>Late submission</strong> \u2014 the application must be filed before visa or visa-free stay expires</li><li><strong>Missing sworn translations</strong> \u2014 all foreign documents require certified translation</li><li><strong>Incomplete documentation</strong> \u2014 missing employer certificates or required attachments</li><li><strong>Form errors</strong> \u2014 spelling mistakes in personal data cause requests for correction</li><li><strong>Missing health insurance</strong> \u2014 often overlooked for contract workers</li></ol><p><a href="/en/uslugi/zezwolenie-na-pobyt-czasowy">Professional help eliminates the risk of refusal</a>.</p>` },
      { id: "faq", heading: "Frequently asked questions about temporary residence cards", content: `<div class="faq-list"><details><summary><strong>How much does a temporary residence card cost in 2026?</strong></summary><p>Stamp duty is 340 PLN (or 440 PLN for unified residence and work permit). Plus 100 PLN for card issuance. With translations and legal assistance, the total cost is 800\u20132,500 PLN.</p></details><details><summary><strong>Can I work while waiting for my residence card?</strong></summary><p>Yes. The passport stamp confirming application submission entitles you to legal work under the conditions specified in the application.</p></details><details><summary><strong>What if my application is rejected?</strong></summary><p>You can appeal to the Head of the Office for Foreigners within 14 days. We help with the appeals process with a 98% success rate.</p></details><details><summary><strong>How long is a temporary residence card valid?</strong></summary><p>It is issued for 3 months to 3 years, depending on the purpose of stay specified in the application.</p></details></div>` },
    ],
  },
  {
    slug: "karta-stalego-pobytu-jak-uzyskac",
    locale: "en",
    title: "Permanent Residence Card in Poland \u2014 Who Can Get It and How to Apply",
    description: "A permanent residence card grants the right to live in Poland indefinitely. Check conditions, documents and costs. Guide by getpermit.pl.",
    date: "2026-04-14",
    imageUrl: "https://images.unsplash.com/photo-1431540015161-0bf868a2d407?w=1600&q=80",
    imageAlt: "Permanent residence card in Poland \u2014 procedure for obtaining the document",
    author: "Grzegorz St\u0119pie\u0144, UTM Group",
    toc: [
      { id: "czym-jest-staly", title: "What is a permanent residence card" },
      { id: "warunki", title: "Eligibility conditions" },
      { id: "dokumenty-staly", title: "Required documents" },
      { id: "koszty-staly", title: "Costs and timelines" },
      { id: "roznice", title: "Permanent residence vs EU long-term resident" },
      { id: "faq-staly", title: "FAQ" },
    ],
    sections: [
      { id: "czym-jest-staly", heading: "What is a permanent residence card and what rights does it grant", content: `<p>A permanent residence card (karta sta\u0142ego pobytu) confirms a foreigner's right to <strong>reside in Poland indefinitely</strong>. Unlike a temporary card, it does not require renewal every few years.</p><ul><li>Indefinite stay in Poland</li><li>Work without a work permit</li><li>Business activity on equal terms with Polish citizens</li><li>Public healthcare and education access</li><li>Eligibility for Polish citizenship</li></ul>` },
      { id: "warunki", heading: "Eligibility conditions for permanent residence", content: `<p>You may apply if you meet <strong>one of the following conditions</strong>:</p><ul><li><strong>Polish heritage</strong> \u2014 proven Polish roots (parents or grandparents were Polish citizens)</li><li><strong>Karta Polaka</strong> \u2014 holder intending to settle permanently in Poland</li><li><strong>Marriage to a Polish citizen</strong> \u2014 at least 3 years of marriage + 2 years of residence on a temporary card</li><li><strong>Victim of human trafficking</strong></li><li><strong>Child of a foreigner</strong> with permanent residence, born in Poland</li></ul><p><a href="/en/uslugi/pobyt-staly">Check if you qualify \u2014 book a consultation</a>.</p>` },
      { id: "dokumenty-staly", heading: "Documents required for permanent residence application", content: `<p>Basic document set:</p><ul><li>Application submitted via the MOS system (Case Handling Module)</li><li>Digital photograph (uploaded via MOS)</li><li>Passport copy (all pages)</li><li>Stamp duty receipt (640 PLN)</li><li>Documents proving your eligibility basis</li></ul><p>All foreign documents require <a href="/en/uslugi/tlumaczenia-przysiegle-dokumentow">sworn translation</a> into Polish.</p>` },
      { id: "koszty-staly", heading: "Costs and processing time for permanent residence", content: `<p>Fees in 2026:</p><ul><li>Stamp duty: <strong>640 PLN</strong></li><li>Card issuance: <strong>100 PLN</strong></li><li>Sworn translations: from 50 PLN per page</li></ul><p>Processing time <strong>depends on the individual case and the workload of the office</strong>. Karta Polaka cases are typically processed faster.</p><p><a href="/en/kontakt">Book a consultation \u2014 we'll prepare your application professionally</a>.</p>` },
      { id: "roznice", heading: "Permanent residence vs EU long-term resident \u2014 differences", content: `<table><thead><tr><th>Feature</th><th>Permanent residence</th><th>EU long-term resident</th></tr></thead><tbody><tr><td>Required stay in Poland</td><td>Not always (depends on basis)</td><td>Min. 5 years of uninterrupted stay</td></tr><tr><td>EU labor market access</td><td>Poland only</td><td>Right to work in other EU countries</td></tr><tr><td>Stamp duty</td><td>640 PLN</td><td>640 PLN</td></tr></tbody></table><p><a href="/en/uslugi/rezydent-dlugoterminowy-ue">Learn more about EU long-term resident status</a>.</p>` },
      { id: "faq-staly", heading: "FAQ \u2014 permanent residence card in Poland", content: `<div class="faq-list"><details><summary><strong>Does a permanent residence card grant Polish citizenship?</strong></summary><p>Not automatically, but after obtaining permanent residence you can apply for citizenship after meeting additional conditions (e.g., Polish language exam at B1 level).</p></details><details><summary><strong>How much does a permanent residence card cost?</strong></summary><p>Stamp duty: 640 PLN + 100 PLN for card issuance. With legal services and translations, the total is typically 1,200\u20133,000 PLN.</p></details><details><summary><strong>Can I lose permanent residence status?</strong></summary><p>Yes, if you leave Poland for more than 6 years or pose a threat to national security.</p></details></div>` },
    ],
  },
  {
    slug: "niebieska-karta-ue-blue-card-2026",
    locale: "en",
    title: "EU Blue Card in Poland 2026 \u2014 New Rules and Requirements",
    description: "EU Blue Card after 2025 changes. Who can get a Blue Card in Poland? Requirements, documents, costs and EU mobility benefits. Guide by getpermit.pl.",
    date: "2026-04-13",
    imageUrl: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1600&q=80",
    imageAlt: "EU Blue Card for specialists in Poland",
    author: "Grzegorz St\u0119pie\u0144, UTM Group",
    toc: [
      { id: "czym-jest-blue", title: "What is the EU Blue Card" },
      { id: "nowe-zasady", title: "Changes from 2025" },
      { id: "wymagania-blue", title: "Requirements" },
      { id: "dokumenty-blue", title: "Required documents" },
      { id: "mobilnosc", title: "EU mobility" },
      { id: "blue-vs-czasowy", title: "Blue Card vs work permit" },
      { id: "faq-blue", title: "FAQ" },
    ],
    sections: [
      { id: "czym-jest-blue", heading: "What is the EU Blue Card and why you should get one", content: `<p>The EU Blue Card is a residence and work permit designed for <strong>highly qualified non-EU workers</strong>. Key advantages:</p><ul><li><strong>EU mobility</strong> \u2014 after 12 months, you can relocate to another EU member state</li><li><strong>Easier family reunification</strong></li><li><strong>Faster path to EU long-term resident</strong> \u2014 periods in different EU countries can be combined</li><li><strong>Simplified procedure</strong> \u2014 fewer formal requirements</li></ul>` },
      { id: "nowe-zasady", heading: "New EU Blue Card rules from 2025 \u2014 what changed", content: `<p>From <strong>June 1, 2025</strong>, revised rules apply. Key changes:</p><ul><li><strong>Lower salary threshold</strong> \u2014 1.0x average salary instead of 1.5x (0.8x for shortage occupations)</li><li><strong>Expanded qualifications</strong> \u2014 3 years of IT experience accepted instead of a degree</li><li><strong>Shorter contracts</strong> \u2014 minimum 6 months (previously 12)</li><li><strong>Short-term mobility</strong> \u2014 up to 90 days of work in another EU country without formalities</li></ul>` },
      { id: "wymagania-blue", heading: "Requirements for the EU Blue Card in Poland", content: `<ol><li><strong>Higher education</strong> (min. 3-year degree) <strong>or 3 years IT experience</strong> (from 2025)</li><li><strong>Employment contract</strong> for at least 6 months with a Polish employer</li><li><strong>Salary</strong> of at least 1.0x the average annual salary (~7,500 PLN gross/month in 2026)</li><li><strong>Health insurance</strong></li><li><strong>Place of residence</strong> in Poland</li></ol><p>IT specialists with 3 years of experience can apply <strong>without a university degree</strong>. <a href="/en/uslugi/eu-blue-card">Check details</a>.</p>` },
      { id: "dokumenty-blue", heading: "Documents required for the EU Blue Card application", content: `<ul><li>Application submitted via the MOS system (Case Handling Module)</li><li>Digital photograph (uploaded via MOS)</li><li>Passport copy</li><li>Employment contract or job promise</li><li>University degree (with nostrification if required) <strong>or</strong> proof of 3 years IT experience</li><li>Salary certificate meeting the threshold</li><li>Health insurance proof</li><li>Stamp duty: <strong>440 PLN</strong> + 100 PLN for card issuance</li></ul>` },
      { id: "mobilnosc", heading: "EU mobility with the Blue Card", content: `<ul><li><strong>Short-term</strong> (up to 90 days) \u2014 business trips without additional formalities</li><li><strong>Long-term</strong> \u2014 after 12 months you can apply for a Blue Card in another EU country on simplified terms</li><li><strong>Period accumulation</strong> \u2014 Blue Card periods in different EU countries count toward the 5-year requirement for EU long-term resident status</li></ul>` },
      { id: "blue-vs-czasowy", heading: "EU Blue Card vs residence and work permit \u2014 comparison", content: `<table><thead><tr><th>Feature</th><th>Blue Card</th><th>Residence & work</th></tr></thead><tbody><tr><td>Salary threshold</td><td>~7,500 PLN gross/mo</td><td>None</td></tr><tr><td>Education</td><td>Degree or 3yr IT exp.</td><td>Any</td></tr><tr><td>Labor market test</td><td>Abolished</td><td>Abolished</td></tr><tr><td>EU mobility</td><td>Yes</td><td>No</td></tr><tr><td>Processing time</td><td>Usually faster</td><td>Depends on office</td></tr></tbody></table><p><a href="/en/kontakt">Not sure which permit is right for you? Book a consultation</a>.</p>` },
      { id: "faq-blue", heading: "FAQ \u2014 EU Blue Card in Poland", content: `<div class="faq-list"><details><summary><strong>What salary is required for a Blue Card in 2026?</strong></summary><p>The threshold is 1.0x the average annual salary, approximately 7,500 PLN gross per month in 2026. In shortage occupations (IT, engineering) the threshold is lower at 0.8x.</p></details><details><summary><strong>Can a programmer without a degree get a Blue Card?</strong></summary><p>Yes, since 2025 IT specialists with at least 3 years of professional experience can apply without a university degree.</p></details><details><summary><strong>How long does the Blue Card procedure take?</strong></summary><p>Processing time depends on the individual case and the workload of the office, but the Blue Card is typically processed faster than a standard residence and work permit.</p></details></div>` },
    ],
  },
  {
    slug: "wnioski-pobytowe-mos-2026",
    locale: "en",
    title: "Online Residence Applications via MOS in 2026 \u2014 How the New System Works",
    description: "Since 2026, residence card applications in Poland are submitted through MOS. How to create an account, fill in the e-application and avoid mistakes. Guide by getpermit.pl.",
    date: "2026-04-12",
    imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=1600&q=80",
    imageAlt: "MOS system \u2014 online residence applications in Poland 2026",
    author: "Grzegorz St\u0119pie\u0144, UTM Group",
    toc: [
      { id: "czym-jest-mos", title: "What is MOS" },
      { id: "jak-zalozyc", title: "How to create an account" },
      { id: "jak-wypelnic", title: "How to fill in the e-application" },
      { id: "zalaczniki", title: "Adding attachments" },
      { id: "po-zlozeniu", title: "After submission" },
      { id: "problemy-mos", title: "Common MOS issues" },
      { id: "faq-mos", title: "FAQ" },
    ],
    sections: [
      { id: "czym-jest-mos", heading: "What is MOS \u2014 the Case Handling Module", content: `<p><strong>MOS (Modu\u0142 Obs\u0142ugi Spraw / Case Handling Module)</strong> is an electronic system launched in 2025 that became the <strong>mandatory channel for submitting residence applications</strong> in Poland from 2026. It replaced paper forms and in-person visits at voivodeship offices at the submission stage.</p><p>Through MOS you can apply for:</p><ul><li>Temporary residence permit</li><li>Permanent residence permit</li><li>EU long-term resident permit</li><li>Residence card replacement</li></ul><p>The system is available at <strong>mos.cudzoziemcy.gov.pl</strong> in Polish, English, Russian and Ukrainian.</p>` },
      { id: "jak-zalozyc", heading: "How to create an account in MOS", content: `<ol><li>Go to <strong>mos.cudzoziemcy.gov.pl</strong></li><li>Click \u201cCreate account\u201d</li><li>Enter your email and create a password</li><li>Confirm your email via the activation link</li><li>Complete your personal details (name, surname, passport number)</li></ol><p>The system allows <strong>saving draft versions</strong> and returning to them at any time.</p>` },
      { id: "jak-wypelnic", heading: "How to fill in the electronic residence application", content: `<p>The MOS form is divided into sections matching the traditional paper form:</p><ol><li><strong>Personal data</strong></li><li><strong>Passport details</strong></li><li><strong>Address in Poland</strong></li><li><strong>Purpose of stay</strong></li><li><strong>Employer data</strong> (if work-related)</li><li><strong>Additional information</strong></li></ol><p>The system <strong>validates data in real time</strong>. <a href="/en/kontakt">Need help filling in the application? Contact us</a>.</p>` },
      { id: "zalaczniki", heading: "Attachments \u2014 what and how to upload", content: `<p>MOS accepts files in PDF, JPG and PNG formats. Maximum <strong>10 MB</strong> per attachment. Required:</p><ul><li>Passport scan (all data pages)</li><li>Biometric photo (digital format)</li><li>Stamp duty payment confirmation</li><li>Documents confirming purpose of stay</li><li>Sworn translations of foreign documents</li></ul><p>Original documents must be presented in person during the <strong>fingerprint appointment</strong>.</p>` },
      { id: "po-zlozeniu", heading: "What happens after submitting via MOS", content: `<ol><li><strong>Case number</strong> assigned</li><li><strong>Electronic confirmation</strong> generated \u2014 equivalent of passport stamp</li><li><strong>Appointment invitation</strong> sent \u2014 for biometrics</li><li><strong>Supplement requests</strong> communicated via MOS and email</li><li><strong>Decision</strong> notification</li></ol>` },
      { id: "problemy-mos", heading: "Common MOS problems and solutions", content: `<ul><li><strong>System overload</strong> \u2014 try submitting in evening hours or on weekends</li><li><strong>Attachment issues</strong> \u2014 ensure files are under 10 MB in PDF/JPG format</li><li><strong>Validation errors</strong> \u2014 check date format (DD-MM-YYYY) and numbers</li><li><strong>Session timeout</strong> \u2014 system logs out after 30 minutes of inactivity; save drafts frequently</li></ul><p><a href="/en/kontakt">Our team can help you submit the application correctly</a>.</p>` },
      { id: "faq-mos", heading: "FAQ \u2014 residence applications via MOS", content: `<div class="faq-list"><details><summary><strong>Can I still submit a paper application?</strong></summary><p>Since 2026, paper applications are accepted only in exceptional cases (e.g., confirmed system failures). The standard channel is MOS exclusively.</p></details><details><summary><strong>Do I need to visit the office in person?</strong></summary><p>Yes \u2014 an in-person visit is required for fingerprint collection (biometrics). The application itself is submitted online.</p></details><details><summary><strong>What languages is MOS available in?</strong></summary><p>Polish, English, Russian and Ukrainian. The application form must be filled in Polish.</p></details></div>` },
    ],
  },
  {
    slug: "ile-kosztuje-karta-pobytu-2026",
    locale: "en",
    title: "How Much Does a Residence Card Cost in 2026? Full Price List",
    description: "Current residence card costs in 2026: stamp duty, card issuance, sworn translations and legal help. Price list and cost calculator by getpermit.pl.",
    date: "2026-04-11",
    imageUrl: "https://images.unsplash.com/photo-1553729459-efe14ef6055d?w=1600&q=80",
    imageAlt: "Residence card costs in Poland 2026 \u2014 official fee price list",
    author: "Grzegorz St\u0119pie\u0144, UTM Group",
    toc: [
      { id: "oplaty-skarbowe", title: "Stamp duties" },
      { id: "wydanie-karty", title: "Card issuance cost" },
      { id: "tlumaczenia", title: "Sworn translations" },
      { id: "pomoc-prawna", title: "Legal assistance" },
      { id: "calkowity-koszt", title: "Total cost" },
      { id: "faq-koszty", title: "FAQ" },
    ],
    sections: [
      { id: "oplaty-skarbowe", heading: "Stamp duties for residence cards in 2026", content: `<table><thead><tr><th>Permit type</th><th>Stamp duty</th></tr></thead><tbody><tr><td>Temporary residence</td><td><strong>340 PLN</strong></td></tr><tr><td>Temporary residence and work (unified)</td><td><strong>440 PLN</strong></td></tr><tr><td>EU Blue Card</td><td><strong>440 PLN</strong></td></tr><tr><td>Permanent residence</td><td><strong>640 PLN</strong></td></tr><tr><td>EU long-term resident</td><td><strong>640 PLN</strong></td></tr></tbody></table><p>The fee must be paid <strong>before submitting the application</strong>.</p>` },
      { id: "wydanie-karty", heading: "Card issuance fee", content: `<p>After a positive decision, the office produces a plastic card. The issuance fee is <strong>100 PLN</strong> for all types. Card production time depends on the office.</p>` },
      { id: "tlumaczenia", heading: "Sworn translation costs", content: `<table><thead><tr><th>Document</th><th>Approximate cost</th></tr></thead><tbody><tr><td>Passport</td><td>50\u2013100 PLN</td></tr><tr><td>Birth certificate</td><td>60\u201380 PLN</td></tr><tr><td>Marriage certificate</td><td>60\u201380 PLN</td></tr><tr><td>University diploma</td><td>80\u2013150 PLN</td></tr></tbody></table><p>Total translation costs for a typical case: <strong>150\u2013400 PLN</strong>. <a href="/en/uslugi/tlumaczenia-przysiegle-dokumentow">We offer competitive translation prices</a>.</p>` },
      { id: "pomoc-prawna", heading: "Cost of professional legal assistance", content: `<ul><li><strong>Initial consultation</strong> \u2014 PLN 250 (approx. 15 min, at getpermit.pl)</li><li><strong>Application preparation</strong> \u2014 from 600 PLN</li><li><strong>Full case handling</strong> \u2014 from 800 PLN</li><li><strong>Permanent / EU resident</strong> \u2014 from 1,200 PLN</li><li><strong>Urgency complaint / appeal</strong> \u2014 from 500 PLN</li></ul><p>Our success rate is <strong>98%</strong>. <a href="/en/kontakt">Book a consultation</a>.</p>` },
      { id: "calkowity-koszt", heading: "Total residence card cost \u2014 summary", content: `<table><thead><tr><th>Component</th><th>Temporary</th><th>Temp. + work</th><th>Permanent</th></tr></thead><tbody><tr><td>Stamp duty</td><td>340 PLN</td><td>440 PLN</td><td>640 PLN</td></tr><tr><td>Card issuance</td><td>100 PLN</td><td>100 PLN</td><td>100 PLN</td></tr><tr><td>Translations</td><td>150\u2013400 PLN</td><td>150\u2013400 PLN</td><td>200\u2013500 PLN</td></tr><tr><td>Legal help (optional)</td><td>from 600 PLN</td><td>from 800 PLN</td><td>from 1,200 PLN</td></tr><tr><td><strong>Total</strong></td><td><strong>590\u20131,440 PLN</strong></td><td><strong>690\u20131,740 PLN</strong></td><td><strong>940\u20132,440 PLN</strong></td></tr></tbody></table>` },
      { id: "faq-koszty", heading: "FAQ \u2014 residence card costs", content: `<div class="faq-list"><details><summary><strong>Is the stamp duty refunded if the application is rejected?</strong></summary><p>No. The stamp duty is non-refundable in case of a negative decision. That's why professional help is recommended to minimize the risk of rejection.</p></details><details><summary><strong>How much does a residence card cost for a Ukrainian citizen?</strong></summary><p>Fees are the same for all foreigners regardless of citizenship. Ukrainians under temporary protection may benefit from simplified procedures, but the fees remain standard.</p></details><details><summary><strong>How much does a consultation at getpermit.pl cost?</strong></summary><p>The initial consultation costs PLN 250 (approx. 15 min). We assess your situation, propose a strategy and provide an exact quote for further services.</p></details></div>` },
    ],
  },
  {
    slug: "wnioski-pobytowe-tylko-przez-mos-od-27-kwietnia-2026",
    locale: "en",
    title: "From 27 April 2026 residence applications only online via MOS — paper applications will not be processed",
    description: "From 27.04.2026 applications for temporary residence, permanent residence and EU long-term residence are submitted only electronically via MOS.",
    date: "2026-06-01",
    imageUrl: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=1600&q=80",
    imageAlt: "Laptop with an online form — electronic residence applications via MOS",
    author: "Zespół getpermit.pl",
    toc: [
      { id: "nowa-procedura", title: "The digital revolution" },
      { id: "wnioski-papierowe", title: "What about paper applications" },
      { id: "jak-dziala", title: "How the new procedure works" },
      { id: "praktyka", title: "What it means in practice" },
    ],
    sections: [
      { id: "nowa-procedura", heading: "From 27 April 2026 residence applications exclusively online via MOS", content: `<p>The digital revolution in residence legalization is here. From 27 April 2026, applications for temporary residence, permanent residence and EU long-term resident permits can be submitted <strong>only electronically</strong> — via the MOS system (Case Handling Module).</p>` },
      { id: "wnioski-papierowe", heading: "What about paper applications?", content: `<p>Paper applications that did not reach voivodeship offices before 27 April 2026 <strong>are not processed</strong> — regardless of the postal date. If you mailed a paper application in late April, verify its status immediately.</p>` },
      { id: "jak-dziala", heading: "How does the new procedure work?", content: `<p>A foreigner creates a free MOS account, fills in the e-application, attaches document scans and a digital photo. The only costs are the stamp duty (depending on permit type) and PLN 100 for the residence card. In work-related procedures the system also involves the employer — an individual link for electronic signing is sent to the employer's e-mail.</p><p>More about the system: <a href="/en/blog/wnioski-pobytowe-mos-2026">Online Residence Applications via MOS in 2026</a>.</p>` },
      { id: "praktyka", heading: "What does it mean in practice?", content: `<p>No more queues in front of offices or last-minute registered letters. But there are new risks: errors in the e-application, problems with the employer's electronic signature or missing attachments can delay the start of proceedings.</p><p><strong>Need help with your MOS application? Book a consultation with getpermit.pl — we will guide you through the entire procedure.</strong></p>` },
    ],
  },
  {
    slug: "rok-nowej-ustawy-o-zatrudnianiu-cudzoziemcow",
    locale: "en",
    title: "One year of Poland's new foreigner employment law — what has actually changed?",
    description: "On 1 June 2025 the act on the admissibility of entrusting work to foreigners entered into force. A 12-month summary: digitalization, end of the labour market test, new duties.",
    date: "2026-06-02",
    imageUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=1600&q=80",
    imageAlt: "Employer and employee handshake — hiring foreigners under the new law",
    author: "Zespół getpermit.pl",
    toc: [
      { id: "elektronizacja", title: "Full digitalization via praca.gov.pl" },
      { id: "koniec-testu", title: "End of the labour market test" },
      { id: "obowiazki", title: "New notification duties" },
      { id: "bilans", title: "The balance sheet" },
    ],
    sections: [
      { id: "elektronizacja", heading: "Full digitalization via praca.gov.pl", content: `<p>On 1 June 2025, the Act of 20 March 2025 on the conditions for the admissibility of entrusting work to foreigners in Poland entered into force. Twelve months on, its impact is clear.</p><p>Work entrustment declarations, work permit applications (including seasonal) and all documents are submitted exclusively electronically via praca.gov.pl. Documents submitted in any other form are rejected.</p>` },
      { id: "koniec-testu", heading: "End of the labour market test", content: `<p>The starost's information was abolished — employers no longer have to prove they could not find a local worker. Procedures shortened by weeks, while offices gained new tools to combat fictitious employment.</p>` },
      { id: "obowiazki", heading: "New notification duties", content: `<p>The employer must notify the office about the start and end of a foreigner's work within set deadlines. Reporting early termination invalidates the declaration. Non-compliance carries real fines.</p>` },
      { id: "bilans", heading: "The balance sheet", content: `<p>Procedures are faster and logistically cheaper, but they require digital discipline: a praca.gov.pl profile, an electronic signature and deadline control are now the basis of legal employment.</p><p><strong>Hiring foreigners? getpermit.pl handles the entire process — from the declaration to your employee's residence card.</strong></p>` },
    ],
  },
  {
    slug: "oplata-400-zl-oswiadczenia-zezwolenia-na-prace",
    locale: "en",
    title: "PLN 400 instead of 100 — higher fees for foreigner work legalization in Poland",
    description: "Since 1 December 2025 the fee for work entrustment declarations and work permit applications rose from PLN 100 to 400. See the current price list.",
    date: "2026-06-03",
    imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=1600&q=80",
    imageAlt: "Calculator and documents — higher fees for work legalization in Poland",
    author: "Zespół getpermit.pl",
    toc: [
      { id: "co-podrozalo", title: "What became more expensive" },
      { id: "kto-ponosi", title: "Who bears the cost" },
      { id: "jak-ograniczyc", title: "How to limit expenses" },
    ],
    sections: [
      { id: "co-podrozalo", heading: "What became more expensive since 1 December 2025?", content: `<p>Since 1 December 2025, regulations raising the fees for documents legalizing foreigners' work have been in force. The fee for submitting a declaration on entrusting work to a foreigner and for work permit applications rose <strong>from PLN 100 to PLN 400</strong>, payable to the account of the competent district labour office.</p>` },
      { id: "kto-ponosi", heading: "Who bears the cost?", content: `<p>The fees are the employer's burden — the law prohibits transferring work legalization costs onto the foreigner. Deducting these amounts from an employee's salary violates the law and risks penalties.</p>` },
      { id: "jak-ograniczyc", heading: "How to limit expenses?", content: `<p>A fourfold higher rate means formal errors cost real money. A declaration rejected for deficiencies means paying again. Verify data before submission on praca.gov.pl, choose the right document type (declaration vs permit) and plan hiring in advance.</p><p><strong>Don't want to pay twice for application errors? getpermit.pl prepares your documents correctly the first time.</strong></p>` },
    ],
  },
  {
    slug: "gruzja-poza-procedura-oswiadczeniowa",
    locale: "en",
    title: "Georgian citizens without declarations — how to legally employ them in 2026?",
    description: "Since 1 December 2025 Georgia has been removed from the declaration procedure. Georgian citizens need a work permit. Check the transition rules.",
    date: "2026-06-04",
    imageUrl: "https://images.unsplash.com/photo-1565008576549-57569a49371d?w=1600&q=80",
    imageAlt: "Tbilisi, Georgia — new rules for employing Georgian citizens in Poland",
    author: "Zespół getpermit.pl",
    toc: [
      { id: "co-sie-zmienilo", title: "What changed" },
      { id: "przepisy-przejsciowe", title: "Transition rules" },
      { id: "co-powinien-pracodawca", title: "What should employers do" },
    ],
    sections: [
      { id: "co-sie-zmienilo", heading: "What changed since 1 December 2025?", content: `<p>Since 1 December 2025, Georgia is no longer on the list of countries covered by the simplified declaration procedure. Previously Georgian citizens — alongside citizens of Ukraine, Belarus, Moldova and Armenia — could work based on a work entrustment declaration registered within days. After the November 2025 regulations, their employment requires a <strong>work permit</strong> or a residence and work permit.</p>` },
      { id: "przepisy-przejsciowe", heading: "Transition rules", content: `<p>Declarations obtained for Georgian citizens before 1 December 2025 remain valid — work based on them is legal until the end of the period indicated in the document. After that, a permit is required.</p>` },
      { id: "co-powinien-pracodawca", heading: "What should employers do?", content: `<p>Plan ahead: work permit proceedings take longer than declaration registration, and the application is filed electronically via praca.gov.pl (fee PLN 400). For workers whose declarations are expiring, it is worth starting the residence-and-work procedure via <a href="/en/blog/wnioski-pobytowe-mos-2026">MOS</a> right away.</p><p><strong>Employing Georgian citizens? We will assess their situation and run the right procedure — book a consultation with getpermit.pl.</strong></p>` },
    ],
  },
  {
    slug: "ees-system-wjazdu-wyjazdu-w-pelni-dziala",
    locale: "en",
    title: "EES fully operational — the end of passport stamps. What foreigners in Poland must know",
    description: "Since 10 April 2026 the EES operates at all Schengen external borders. Biometrics instead of stamps and automatic 90/180-day counting.",
    date: "2026-06-05",
    imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=1600&q=80",
    imageAlt: "Airport border control — the EES records entries and exits in the Schengen area",
    author: "Zespół getpermit.pl",
    toc: [
      { id: "jak-dziala-ees", title: "How does EES work" },
      { id: "liczenie-90-180", title: "Automatic 90/180 counting" },
      { id: "posiadacze-kart", title: "What about residence card holders" },
    ],
    sections: [
      { id: "jak-dziala-ees", heading: "How does EES work?", content: `<p>The EU Entry/Exit System (EES), rolled out in stages from 12 October 2025, has been fully operational at the Schengen external borders since 10 April 2026 — including Polish border crossings and airports.</p><p>The system electronically records every external border crossing by a third-country national on a short stay: passport data, fingerprints and a facial image. Traditional passport stamps are history.</p>` },
      { id: "liczenie-90-180", heading: "Automatic 90/180 counting", content: `<p>EES automatically calculates the use of the 90-days-in-180 limit. Overstays that previously went unnoticed are now flagged automatically — and visible to border services of all member states.</p>` },
      { id: "posiadacze-kart", heading: "What about residence card holders?", content: `<p>Foreigners holding a Polish residence card or long-term visa <strong>are not registered in EES</strong> — the system covers short stays only. One more reason to settle your residence status instead of relying on visa-free travel.</p><p><strong>Running out of your 90/180 limit? We will help you legalize a long-term stay — book a consultation with getpermit.pl.</strong></p>` },
    ],
  },
  {
    slug: "etias-od-konca-2026-co-musisz-wiedziec",
    locale: "en",
    title: "ETIAS from late 2026 — travel authorization for 20 euro. Who needs it?",
    description: "In Q4 2026 ETIAS launches — electronic travel authorization for citizens of 59 visa-free countries. EUR 20 fee, 3-year validity, transition period.",
    date: "2026-06-06",
    imageUrl: "https://images.unsplash.com/photo-1452421822248-d4c2b47f0c81?w=1600&q=80",
    imageAlt: "Passport and travel documents — ETIAS authorization for visa-free travellers to the EU",
    author: "Zespół getpermit.pl",
    toc: [
      { id: "kogo-obejmie", title: "Who will ETIAS cover" },
      { id: "koszt-waznosc", title: "Cost and validity" },
      { id: "wylaczenia", title: "Transition period and exemptions" },
    ],
    sections: [
      { id: "kogo-obejmie", heading: "Who will ETIAS cover?", content: `<p>In the fourth quarter of 2026, ETIAS — the European Travel Information and Authorisation System — is set to launch. It will cover citizens of 59 visa-exempt countries and territories — including Ukraine, Georgia and the UK — travelling to 30 European countries for stays of up to 90 days in any 180-day period.</p>` },
      { id: "koszt-waznosc", heading: "Cost and validity", content: `<p>The fee is <strong>EUR 20</strong> (raised by the European Commission in July 2025 from the planned EUR 7). The authorization will be valid for 3 years or until the passport expires. Travellers under 18 and over 70 are exempt from the fee.</p>` },
      { id: "wylaczenia", heading: "Transition period and exemptions", content: `<p>After launch, a transition period of at least 6 months is planned, during which the authorization will be optional. ETIAS <strong>does not apply</strong> to holders of residence cards and long-term visas — people with settled status in Poland travel without it.</p><p><strong>Not sure whether ETIAS will apply to you or your employees? Ask the getpermit.pl experts.</strong></p>` },
    ],
  },
  {
    slug: "niebieska-karta-ue-nowy-prog-wynagrodzenia-2026",
    locale: "en",
    title: "EU Blue Card in 2026 — new salary threshold of PLN 13,355.34 gross",
    description: "From 2026 the Blue Card salary threshold in Poland is PLN 13,355.34 gross. New requirements: contract from 6 months and recognition of professional experience.",
    date: "2026-06-08",
    imageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&q=80",
    imageAlt: "Modern office building — EU Blue Card for highly qualified professionals",
    author: "Zespół getpermit.pl",
    toc: [
      { id: "nowy-prog", title: "New threshold PLN 13,355.34 gross" },
      { id: "lagodniejsze-warunki", title: "Other conditions relaxed" },
      { id: "dlaczego-warto", title: "Why it is worth it" },
    ],
    sections: [
      { id: "nowy-prog", heading: "New threshold: PLN 13,355.34 gross", content: `<p>Professionals applying for the EU Blue Card in Poland must demonstrate a higher salary in 2026. According to the Statistics Poland (GUS) announcement of 9 February 2026, the average salary in the national economy in 2025 was PLN 8,903.56 gross. The Blue Card threshold is 150% of that amount — in proceedings initiated in 2026 the salary must be at least <strong>PLN 13,355.34 gross per month</strong>.</p>` },
      { id: "lagodniejsze-warunki", heading: "Other conditions relaxed", content: `<p>Following the new Blue Card directive, the procedure has been partially unified across the EU: a contract for <strong>at least 6 months</strong> suffices (previously 12), and in some professions — especially IT — higher qualifications can be proven by <strong>professional experience</strong> instead of a university diploma. More about the Blue Card: <a href="/en/blog/niebieska-karta-ue-blue-card-2026">EU Blue Card in Poland 2026</a>.</p>` },
      { id: "dlaczego-warto", heading: "Why is it worth it?", content: `<p>The Blue Card offers a faster path to EU long-term resident status, easier mobility to other member states and more favourable family reunification rules. The card is issued for up to 3 years and is renewable.</p><p><strong>Do you meet the Blue Card conditions? We will assess your case and handle the MOS application — book a consultation with getpermit.pl.</strong></p>` },
    ],
  },
  {
    slug: "jednolite-zezwolenie-dyrektywa-single-permit-2026",
    locale: "en",
    title: "Unified Residence and Work Permit under the New Single Permit Directive — Poland from 22 May 2026",
    description: "From 22.05.2026 Poland applies the new single permit directive 2024/1233. Unified residence and work permit — shorter deadlines, extended workers' rights and new employer duties.",
    date: "2026-06-09",
    imageUrl: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1600&q=80",
    imageAlt: "Signing a contract — unified residence and work permit under the single permit directive 2024/1233",
    author: "Zespół getpermit.pl",
    toc: [
      { id: "czym-jest-single", title: "What is the single permit" },
      { id: "co-zmienia-dyrektywa", title: "What directive 2024/1233 changes" },
      { id: "terminy", title: "Shorter processing deadlines" },
      { id: "prawa-pracownika", title: "Worker rights" },
      { id: "praktyczne-skutki", title: "Practical effects for employers" },
    ],
    sections: [
      { id: "czym-jest-single", heading: "What is the unified residence and work permit (single permit)?", content: `<p>The single permit is one document — the residence card — combining the right to reside and work in Poland. It replaces separate procedures: a residence permit and a separate work permit. From 22 May 2026, Poland applies the revised directive 2024/1233, updating the earlier directive 2011/98/EU.</p>` },
      { id: "co-zmienia-dyrektywa", heading: "What does directive 2024/1233 change?", content: `<ul><li><strong>Single window</strong> — one authority handles the entire residence-and-work procedure</li><li><strong>Simplified information access</strong> — the foreigner must receive a written explanation of their rights</li><li><strong>Equal treatment</strong> — single permit holders have the same rights to training, leave and benefits as EU citizens</li><li><strong>Protection against abuse</strong> — employers cannot condition continued employment on withholding information about working conditions</li></ul>` },
      { id: "terminy", heading: "Shorter processing deadlines", content: `<p>Directive 2024/1233 obliges member states to process single permit applications within <strong>90 days</strong> of submission of complete documentation. The new rules strengthen the right to file urgency complaints in case of delays.</p>` },
      { id: "prawa-pracownika", heading: "Worker rights with the single permit", content: `<p>Single permit holders are entitled to:</p><ul><li>The same pay as domestic workers in the same position</li><li>Freedom to join trade unions</li><li>Annual leave and sick leave on the same terms</li><li>Transfer to another employer subject to permit conditions</li></ul>` },
      { id: "praktyczne-skutki", heading: "Practical effects for employers", content: `<p>Employers must ensure that single permit holders are not discriminated against in pay and working conditions. Charging workers for recruitment and legalization costs is prohibited. Violations may result in financial penalties and loss of the ability to employ foreigners.</p><p><strong>Questions about the single permit after the changes? Contact getpermit.pl — we advise both employers and workers.</strong></p>` },
    ],
  },
  {
    slug: "placa-minimalna-2026-a-legalizacja-pracy-cudzoziemcow",
    locale: "en",
    title: "PLN 4,806 Minimum Wage in 2026 and Work Legalization for Foreigners",
    description: "From 1 January 2026 the minimum wage is PLN 4,806 gross (PLN 31.40/h). See how the wage increase affects work declarations and permits for foreigners.",
    date: "2026-06-10",
    imageUrl: "https://images.unsplash.com/photo-1579621970795-87facc2f976d?w=1600&q=80",
    imageAlt: "Banknotes and documents — minimum wage PLN 4,806 and work legalization for foreigners in 2026",
    author: "Zespół getpermit.pl",
    toc: [
      { id: "aktualne-stawki", title: "Current rates from 1 January 2026" },
      { id: "wplyw-na-oswiadczenia", title: "Effect on work entrustment declarations" },
      { id: "wplyw-na-zezwolenia", title: "Effect on work permits" },
      { id: "obowiazki-pracodawcy", title: "Employer obligations" },
    ],
    sections: [
      { id: "aktualne-stawki", heading: "Current rates from 1 January 2026", content: `<p>From 1 January 2026, the minimum wage is <strong>PLN 4,806 gross</strong> per month and the minimum hourly rate is <strong>PLN 31.40 gross</strong>. The increase of over 5% compared to 2025 directly affects work legalization conditions for foreigners.</p>` },
      { id: "wplyw-na-oswiadczenia", heading: "Effect on work entrustment declarations", content: `<p>A work entrustment declaration must state a salary at least equal to the minimum wage. If a previously submitted declaration states a salary below PLN 4,806 gross, this may cause problems during Labour Inspectorate checks. Employers should update employment conditions with an annex or a new declaration.</p>` },
      { id: "wplyw-na-zezwolenia", heading: "Effect on work permits", content: `<p>A work permit is issued for a specific position and salary. If the salary stated in the permit is below the current minimum, the employer is obliged to pay the worker at least the minimum rate. When filing new applications, always state a salary of \u2265 PLN 4,806 gross.</p>` },
      { id: "obowiazki-pracodawcy", heading: "Employer obligations", content: `<p>An employer hiring a foreigner cannot pay below the statutory minimum regardless of what the declaration or permit states. Non-compliance risks:</p><ul><li>A fine for violating minimum wage provisions</li><li>Revocation of the work permit</li><li>Inclusion on the list of entities with restrictions on employing foreigners</li></ul><p><strong>Want to make sure your employment documents comply with current regulations? Consult getpermit.pl.</strong></p>` },
    ],
  },
  {
    slug: "pracodawca-w-systemie-mos-podpis-elektroniczny",
    locale: "en",
    title: "Employer in the MOS System — Electronic Signature and Work-Permit Email Link Explained",
    description: "Since 27.04.2026 employers participate in the MOS procedure via email and electronic signature. How it works, what the employer signs and penalties for refusal.",
    date: "2026-06-11",
    imageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=1600&q=80",
    imageAlt: "Laptop and electronic signature — employer in the MOS system for foreigner work legalization",
    author: "Zespół getpermit.pl",
    toc: [
      { id: "jak-dziala-link", title: "How the employer link in MOS works" },
      { id: "co-podpisuje", title: "What the employer signs" },
      { id: "podpis-elektroniczny", title: "Required electronic signature" },
      { id: "co-jesli-odmowa", title: "What if the employer refuses" },
    ],
    sections: [
      { id: "jak-dziala-link", heading: "How does the employer link in the MOS system work?", content: `<p>In work-related residence procedures via MOS the employer is an active participant — not only issuing documents but confirming their participation electronically. When a foreigner submits an application in MOS, the system automatically generates an <strong>individual link</strong> and sends it to the employer's e-mail address stated in the application. Under that link the employer logs in and signs the required documents.</p>` },
      { id: "co-podpisuje", heading: "What does the employer sign?", content: `<p>Depending on the procedure type, the employer electronically confirms:</p><ul><li>The content of the work entrustment declaration — accuracy of data and actual employment conditions</li><li>Attachment no. 1 to the residence and work permit application — employer data and employment conditions</li><li>Commitment to employ the foreigner on the terms stated in the application</li></ul>` },
      { id: "podpis-elektroniczny", heading: "Required electronic signature", content: `<p>The MOS system accepts the following forms of employer signature:</p><ul><li><strong>Trusted Profile (Profil Zaufany)</strong> — free electronic signature confirmed via ePUAP, accessible via e-banking or a chip-enabled ID card</li><li><strong>Qualified electronic signature</strong> — paid service from certified providers (e.g. Certum, Autenti), legally equivalent to a handwritten signature</li></ul><p>The employer must have a MOS account or register before signing. The time to sign documents is limited — usually 7\u201314 days from the link being sent.</p>` },
      { id: "co-jesli-odmowa", heading: "What if the employer refuses or does not respond?", content: `<p>Failure to sign within the deadline causes the <strong>suspension or discontinuation of proceedings</strong>. Employers who systematically refuse to participate in MOS procedures may be placed on the list of entities with restrictions on employing foreigners.</p><p><strong>Need help registering an employer in MOS or with the electronic signature? Our team will guide you through the entire process — contact getpermit.pl.</strong></p>` },
    ],
  },
];
