-- Parser v1.2 — new FdkBaseType enum values per department instructions 02.10.2026
ALTER TYPE "FdkBaseType" ADD VALUE IF NOT EXISTS 'OD_BLUE_CARD';
ALTER TYPE "FdkBaseType" ADD VALUE IF NOT EXISTS 'OD_MALZONEK_PL';
ALTER TYPE "FdkBaseType" ADD VALUE IF NOT EXISTS 'OD_CZLONEK_RODZINY';
ALTER TYPE "FdkBaseType" ADD VALUE IF NOT EXISTS 'OD_HUMANITARNE';
ALTER TYPE "FdkBaseType" ADD VALUE IF NOT EXISTS 'POBYT_CUKR';
