-- Calendar: DONE status
ALTER TABLE "calendar_events" ADD COLUMN "done" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "calendar_events" ADD COLUMN "done_at" TIMESTAMP;

-- Extend CalendarEventType
ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'DOCUMENT_EXPIRY';
ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'WORK_START_REMINDER';
ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'CONTRACT_REMINDER';
ALTER TYPE "CalendarEventType" ADD VALUE IF NOT EXISTS 'WORK_NOTIFICATION';
